'use client'

import React, { useEffect, useRef, useState } from 'react';
import rough from 'roughjs';

const ProjectSchematics = ({ projectDescription }) => {
  const canvasRef = useRef(null);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  // 1. SIMULATED API CALL (Replace with your actual Gemini API fetch)
  useEffect(() => {
    const fetchSchematic = async () => {
      setLoading(true);
      // In production, fetch from your /api/gemini route
      // Here is a mock response based on your "DevFlow" project
      const mockResponse = {
        nodes: [
          { id: 1, label: 'Jira/GitHub', x: 50, y: 100 },
          { id: 2, label: 'T3 Engine', x: 200, y: 100 },
          { id: 3, label: 'Dashboard', x: 350, y: 100 },
          { id: 4, label: 'Prisma DB', x: 200, y: 200 },
        ],
        links: [
          { from: 1, to: 2 },
          { from: 2, to: 3 },
          { from: 2, to: 4 },
        ]
      };

      setTimeout(() => {
        setData(mockResponse);
        setLoading(false);
      }, 1500); // Simulate AI thinking
    };

    fetchSchematic();
  }, [projectDescription]);

  // 2. ROUGH.JS DRAWING LOGIC
  useEffect(() => {
    if (!loading && data && canvasRef.current) {
      const canvas = canvasRef.current;
      const rc = rough.canvas(canvas);
      const ctx = canvas.getContext('2d');
      ctx.clearRect(0, 0, canvas.width, canvas.height); // Clear for redraws

      const strokeColor = '#2d2d2d';
      const accentColor = '#d97706'; // Your orange

      // Draw Links
      data.links.forEach(link => {
        const start = data.nodes.find(n => n.id === link.from);
        const end = data.nodes.find(n => n.id === link.to);
        rc.line(start.x, start.y, end.x, end.y, { 
          roughness: 2.5, 
          stroke: strokeColor, 
          strokeWidth: 1,
          bowing: 2
        });
      });

      // Draw Nodes
      data.nodes.forEach(node => {
        // Draw the box
        rc.rectangle(node.x - 40, node.y - 20, 80, 40, {
          roughness: 1.5,
          stroke: strokeColor,
          fill: `${accentColor}15`, // Light orange tint
          fillStyle: 'hachure',
          hachureAngle: 60,
          hachureGap: 4
        });

        // Draw the text (Standard canvas text)
        ctx.font = '10px "Courier New", monospace';
        ctx.fillStyle = strokeColor;
        ctx.textAlign = 'center';
        ctx.fillText(node.label.toUpperCase(), node.x, node.y + 4);
      });
    }
  }, [data, loading]);

  return (
    <div className="schematic-container" style={{ position: 'relative', width: '100%', height: '300px' }}>
      {loading && (
        <div style={{
          position: 'absolute', top: '40%', left: '10%',
          fontFamily: '"Courier New", monospace', fontSize: '12px', color: '#d97706'
        }}>
          &gt; INITIALIZING_GEMINI_DRAUGHTSMAN...<br/>
          &gt; PARSING_PROJECT_STRUCTURE...<br/>
          &gt; GENERATING_SCHEMATIC...
        </div>
      )}
      <canvas 
        ref={canvasRef} 
        width={450} 
        height={300} 
        style={{ width: '100%', height: 'auto', opacity: loading ? 0 : 1, transition: 'opacity 0.5s' }}
      />
      <div style={{
        marginTop: '10px', fontSize: '9px', fontStyle: 'italic', opacity: 0.5, textAlign: 'right'
      }}>
        Generated by FieldNotes AI v1.0
      </div>
    </div>
  );
};

export default ProjectSchematics;